#!/bin/bash

# Load up OS-specific settings
. /etc/os-release
. functions.general

if [ -n "${ID}" -a -f functions.${ID} ]; then
  . functions.${ID}
else
  echo "Error: no OS-specific functions for this system, exiting."
  exit 1
fi

cd ${BASEDIR}
FUNCTION_LIST="
    install_dependencies
    add_puppet_repository
    install_puppet
    configure_puppetmaster
    restart_apache
    create_minimal_manifest
    test_puppet_client
    install_puppetdb
    create_larger_manifest
    restart_apache
    configure_puppetdb_via_puppet
    verify_puppetdb_works
    "
# FUNCTION_LIST="$*"
for name in ${FUNCTION_LIST}; do
  echo === Running ${name}\(\) ===
  ${name}
  echo
  # echo Press enter to continue
  # read junk
done
