#!/bin/bash
DEBIAN_RELEASE="squeeze"
BACKPORTS_REPO="http://backports.debian.org/debian-backports"
PUPPET_REPO="http://apt.puppetlabs.com"
OTHER_DEPENDS="
  xemacs21
"
PUPPET_PACKAGES="
  puppet
  puppet-el
  puppetmaster-passenger
"
APT_OPTIONS='-q -y'

function add_backports_repository()
{
# Add backports for nginx and other packages if needed
    grep -q ${BACKPORTS_REPO} /etc/apt/sources.list || \
	echo "deb ${BACKPORTS_REPO} ${DEBIAN_RELEASE}-backports main" \
	>> /etc/apt/sources.list
    apt-get -q update > /dev/null
}

function add_puppet_repository()
{
# Add puppet repository for later puppet releases
    grep -q ${PUPPET_REPO} /etc/apt/sources.list || \
	echo "deb ${PUPPET_REPO} ${DEBIAN_RELEASE} main" \
	>> /etc/apt/sources.list
    wget -O puppet_repo.gpg ${PUPPET_REPO}/pubkey.gpg
    apt-key add puppet_repo.gpg
    apt-get -q update > /dev/null
}

function install_dependencies()
{
# Install required packages interactively, so mysql-server can
# prompt for a root password
    apt-get ${APT_OPTIONS} install ${OTHER_DEPENDS}
}

function install_puppet()
{
# Install puppet packages
    apt-get ${APT_OPTIONS} --install-recommends install ${PUPPET_PACKAGES}
}

function configure_puppetmaster()
{
# Create puppet.conf, including storeconfigs support
    cp puppet.conf /etc/puppet/puppet.conf
    perl -pi.bak \
	-e "s/__FQDN__/${FQDN}/g" \
	/etc/puppet/puppet.conf
	chmod 600 /etc/puppet/puppet.conf
    mkdir /etc/puppet/plugins
}

function restart_apache()
{
	/etc/init.d/apache2 restart
}

function create_minimal_manifest()
{
# Finishing up minimal puppet manifests
    mkdir -p /etc/puppet/environments/dev/manifests
    if [ ! -f /etc/puppet/environments/dev/manifests/site-dev.pp ]; then
	echo 'node default {}' > /etc/puppet/environments/dev/manifests/site-dev.pp
    fi
}

function test_puppet_client()
{
    puppet agent -vt
}

BASEDIR=`dirname $0`
FQDN=`hostname --fqdn`

cd ${BASEDIR}
FUNCTION_LIST="
	add_backports_repository
	add_puppet_repository
	install_dependencies
	install_puppet
	configure_puppetmaster
	restart_apache
	create_minimal_manifest
	test_puppet_client
	"
for name in ${FUNCTION_LIST}; do
  echo === Running ${name}\(\) ===
  ${name}
  echo
done
